@extends('store.layout', ['hideHeader'=>true, 'hideFooter'=>true])
@section('title', 'كاتالوج VERO')
@section('content')
<main class="photo-catalog"><header class="photo-catalog-header"><a class="photo-catalog-brand" href="{{ route('home') }}" aria-label="VERO — الصفحة الرئيسية">VERO</a><h1>الكاتالوج</h1><button type="button" onclick="navigator.clipboard.writeText(location.href).then(()=>this.textContent='تم نسخ الرابط')">مشاركة الرابط</button></header><p class="photo-catalog-color-note">يمكنك اختيار أي لون ظاهر في الصور وطلبه على الموديل الذي تريده.</p><nav class="photo-catalog-filters" aria-label="أقسام الكاتالوج"><button type="button" aria-pressed="true" data-filter="all">الكل</button>@foreach(['formal'=>'كلاسيك','casual'=>'كاجوال','sport'=>'سبور','boot'=>'بوط','medical'=>'طبي'] as $category=>$label)<button type="button" aria-pressed="false" data-filter="{{ $category }}">{{ $label }}</button>@endforeach</nav>
@foreach(['formal'=>'كلاسيك','casual'=>'كاجوال','sport'=>'سبور','boot'=>'بوط','medical'=>'طبي'] as $category=>$label)
@if(($photos[$category] ?? collect())->isNotEmpty())<section class="photo-catalog-section" data-category="{{ $category }}"><h2>{{ $label }}<span class="photo-catalog-section-details">{{ $headingNote }}</span></h2><div class="photo-catalog-grid">@foreach($photos[$category] as $photo)<button type="button" class="photo-catalog-card" data-image="{{ $photo->image_path }}" data-code="{{ $photo->code }}" data-alt="{{ $photo->alt }}"><img src="{{ $photo->image_path }}" alt="{{ $photo->alt }}" loading="lazy" width="600" height="600"><span dir="ltr" translate="no">{{ $photo->code }}</span></button>@endforeach</div></section>@endif
@endforeach
<dialog class="photo-catalog-dialog" id="catalog-dialog"><div class="photo-catalog-enlarged"><div><strong id="dialog-code" dir="ltr"></strong><button type="button" id="dialog-close">إغلاق ×</button></div><img id="dialog-image" alt=""></div></dialog></main>
<script>document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===button?'true':'false'));document.querySelectorAll('[data-category]').forEach(section=>section.hidden=button.dataset.filter!=='all'&&section.dataset.category!==button.dataset.filter)}));const catalogDialog=document.getElementById('catalog-dialog');document.querySelectorAll('.photo-catalog-card').forEach(button=>button.addEventListener('click',()=>{document.getElementById('dialog-code').textContent=button.dataset.code;document.getElementById('dialog-image').src=button.dataset.image;document.getElementById('dialog-image').alt=button.dataset.alt;catalogDialog.showModal()}));document.getElementById('dialog-close').addEventListener('click',()=>catalogDialog.close());catalogDialog.addEventListener('click',event=>{if(event.target===catalogDialog)catalogDialog.close()});</script>
@endsection
