@extends('store.layout')
@section('title', $product->name.' | VERO')
@section('description', $product->name.' من VERO. '.$product->description)
@section('content')
@php($images = collect([['color'=>'الأساسية','imagePath'=>$product->image_path]])->merge($product->color_images ?? [])->unique('imagePath')->values())
<main class="product-detail wrap"><a class="product-back" href="{{ route('home') }}">الرجوع إلى الصفحة الرئيسية</a><div class="product-detail-grid">
<div class="product-gallery"><img id="product-main-image" src="{{ $product->image_path }}" alt="{{ $product->name }}" style="width:100%;max-height:650px;object-fit:contain;background:white"><div class="product-gallery-thumbs">@foreach($images as $image)<button type="button" onclick="document.getElementById('product-main-image').src=this.dataset.image" data-image="{{ $image['imagePath'] }}" aria-label="عرض صورة {{ $image['color'] }}"><img src="{{ $image['imagePath'] }}" alt=""><span>{{ $image['color'] }}</span></button>@endforeach</div></div>
<div class="product-detail-info"><div class="kicker">VERO · صناعة لبنانية</div><h1>{{ $product->name }}</h1>@if($product->catalog_code)<p class="product-catalog-code">كود الموديل: <bdi>{{ $product->catalog_code }}</bdi></p>@endif<p>{{ $product->description }}</p><strong class="product-detail-price">${{ number_format($product->sellingPrice(), 2) }}</strong>@if($product->sellingPrice() < (float)$product->price)<p><del>${{ number_format((float)$product->price, 2) }}</del> · خصم {{ $product->discount_type === 'percent' ? $product->discount_value.'%' : '$'.$product->discount_value }}</p>@endif
<form class="product-detail-options product-purchase" data-product-id="{{ $product->id }}"><fieldset><legend>اختار اللون</legend><div class="product-color-boxes">@foreach($product->colors ?? [] as $color)<label class="purchase-color"><input type="radio" name="color" value="{{ $color }}" required><span>{{ $color }}</span></label>@endforeach</div></fieldset><fieldset><legend>اختار المقاس</legend><div class="purchase-sizes">@foreach($product->sizes ?? [] as $size)<label><input type="radio" name="size" value="{{ $size }}" required><span>{{ $size }}</span></label>@endforeach</div></fieldset><label class="purchase-quantity">الكمية<select name="quantity">@for($i=1;$i<=10;$i++)<option value="{{ $i }}">{{ $i }}</option>@endfor</select></label><button type="submit" class="shop-add" disabled>أضف إلى السلة · ${{ number_format($product->sellingPrice(), 2) }}</button><p class="purchase-error" role="alert" hidden></p></form>
@if($product->fit_note || count($product->size_guide ?? []))<details class="size-guide"><summary>دليل المقاسات لهالموديل</summary>@if($product->fit_note)<p>{{ $product->fit_note }}</p>@endif
@if(count($product->size_guide ?? []))<table><thead><tr><th>النمرة</th><th>طول القدم المناسب (سم)</th><th>العرض عند المشط (سم)</th></tr></thead><tbody>@foreach($product->size_guide as $row)<tr><td>{{ $row['size'] ?? '' }}</td><td>{{ $row['footLengthCm'] ?? '' }}</td><td>{{ $row['ballWidthCm'] ?? '—' }}</td></tr>@endforeach</tbody></table>@endif</details>@endif
<p class="custom-sizing-note">يمكن تعديل المقاسات للحالات الخاصة. تواصلوا معنا لتحديد الطول والعرض المناسبين قبل تأكيد الطلب.</p><div class="product-detail-actions"><a class="button" href="https://wa.me/{{ $whatsapp }}?text={{ rawurlencode('مرحباً VERO، بدي استفسر عن '.$product->name.': '.route('products.show', $product)) }}" target="_blank" rel="noopener noreferrer">استفسر عن هذا الموديل عبر واتساب</a><button type="button" class="button" onclick="navigator.clipboard.writeText(location.href).then(()=>this.textContent='تم نسخ الرابط')">مشاركة الرابط</button><a class="button home-return" href="{{ route('home') }}">الرجوع إلى الصفحة الرئيسية</a></div>@if($policy)<details class="returns-policy product-returns"><summary>سياسة التبديل والإرجاع</summary><p class="store-page-text">{{ $policy->body }}</p></details>@endif<p class="product-detail-note">منأكّد اللون والمقاس المتوفرين وأجرة التوصيل قبل تجهيز الطلب.</p></div>
</div></main>
@endsection
